# Generated by Django 3.1.1 on 2020-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('sound', models.CharField(choices=[('S', 'Strings'), ('P', 'Percussion'), ('W', 'Woodwind'), ('B', 'Brass'), ('V', 'Vocals')], max_length=1)),
            ],
        ),
    ]
