# Generated by Django 3.1.1 on 2020-09-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.album'),
            preserve_default=False,
        ),
    ]
